

GET http://localhost:5000/api/products
Authorization: Bearer <eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MDczMTU4MCwiaWF0IjoxNzYwNjQ1MTgwfQ.IkbhGtRq7BktZb8w45kyq98LWU9pdVfWd4DnVwaZ70w>
Accept: application/json
### REGISTER USER

POST http://localhost:5000/api/users/register
Accept: application/json
Content-Type: application/json

{
  "username": "alsya123",
  "email": "alsya007@gmail.com",
  "password": "alsya123"
}

### LOGIN USER
POST http://localhost:5000/api/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "alsya007@gmail.com",
  "password": "alsya123"
}


### CREAT NEW PRODUCT

POST http://localhost:5000/api/products
x-api-key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "BACOK KERAS",
  "price": 10000000,
  "description": "Laptop Gaming RAM 16GB SSD 1TB"
}

### UPDATE PRODUCT
PUT http://localhost:5000/api/products/6
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "price": 19000000,
  "description": "Laptop Gaming RAM 8GB SSD 1TB"
}

### GET PRODUCT BY ID
GET http://localhost:5000/api/products/9
Accept: application/json


### DELETE PRODUCT
DELETE http://localhost:5000/api/products/2
Accept: application/json


GET