

GET http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MDk5ODI2OSwiaWF0IjoxNzYwOTExODY5fQ.eGi_i6IHgqfU5tKjbQy5ZCme7vy3-71-W_55dvK6RnI
Accept: application/json

### REGISTER USER
POST http://localhost:5000/api/users/register
Accept: application/json
Content-Type: application/json

{
  "username": "fazel123",
  "email": "alsya008@gmail.com",
  "password": "alsya123"
}

### LOGIN USER
POST http://localhost:5000/api/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "alsya008@gmail.com",
  "password": "alsya123"
}


### CREAT NEW POST

POST http://localhost:5000/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MTIzODUxMSwiaWF0IjoxNzYxMTUyMTExfQ.Ou7HWPpLf5AAAWpmbBvQ1SdFuwWut3qK8_rzP8Qr-28
Content-Type: application/json

{
  "title": "SAHRONI MASUK KADANG BABI DAN DITANGKAP POLISI SUMPAH 3",
  "content": "INI BERITA HOAX KEDUA",
  "image_url": "www.image.com/fazel225.jpg"
}

### GET PRODUCT BY ID
GET http://localhost:5000/api/posts/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MTIzODUxMSwiaWF0IjoxNzYxMTUyMTExfQ.Ou7HWPpLf5AAAWpmbBvQ1SdFuwWut3qK8_rzP8Qr-28
Accept: application/json


### DELETE PRODUCT
DELETE http://localhost:5000/api/posts/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo4LCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MTA3ODQzOSwiaWF0IjoxNzYwOTkyMDM5fQ.aBxS6IdFiSEmyjVNS3wcvPoQYv6qOmfguRa42NJnvnk
Accept: application/json

### UPDATE NEW POST
PUT http://localhost:5000/api/posts/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MTI0MTA4NywiaWF0IjoxNzYxMTU0Njg3fQ.-T_N_t9AijJflT43sCNs9kd33hZ3jW-_st0EKCF2vQQ
Content-Type: application/json

{
  "title": "SAHRONI MASUK KADANG",
  "content": "ASFBASOIVBASVNBIASNVSANVPOANSVPOSANV",
  "image_url": "www.image.com/alsya.jpg"
}

### CREATE COMMENT
POST http://localhost:5000/api/posts/99/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJpc3MiOiJiZWxhamFyLXJlc3QtYXBpLWdvbGFuZyIsImV4cCI6MTc2MTI0MTA4NywiaWF0IjoxNzYxMTU0Njg3fQ.-T_N_t9AijJflT43sCNs9kd33hZ3jW-_st0EKCF2vQQ
Content-Type: application/json

{
  "content": "WOKWOKWOWKOWKOWKJAJAJAJAhahah"
}